---
- hosts: remoteserver
  become: true
  vars_files:
    - ./group_vars/etc/default.yml
    
  tasks:
    - name:  Run Nginx Docker Container
      block: 
        - name: Pull default Docker image
          docker_image:
            name: "{{ default_container_image }}"
            source: pull

    # Creates the number of containers defined by the variable create_containers, using values from vars file
        - name: Create default containers
          docker_container:
            name: "{{ default_container_name }}"
            image: "{{ default_container_image }}"
            state: started
            ports:
              - "80:80"
    - name:  Run Docker Monitor Script
      block:
        - name: Transfer container usage monitor script 
          copy:
             src: ./script/container_monitor.sh 
             dest: /usr/local/bin 
             mode: 0775
        - name: run monitor script 
          shell: nohup /usr/local/bin/container_monitor.sh &

