---
- hosts: remoteserver
  become: true
  vars_files:
     - ./group_vars/etc/default.yml

  tasks:
    - name: Install Docker-ce and dependency 
      block:
      - name: Install aptitude using apt
        apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

      - name: Install required system packages
        apt: name={{ item }} state=latest update_cache=yes
        loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

      - name: Add Docker GPG apt Key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Add Docker Repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present

      - name: Update apt and install docker-ce
        apt: update_cache=yes name=docker-ce state=latest

      - name: Install Docker Module for Python
        pip:
          name: docker
    - name: SetUp OS Firewall
      block:
      - name: enable ssh 
        ufw:
          rule: allow
          port: ssh
      - name: allow http
        ufw:
          rule: allow
          port: http
      - name: Enable ufw
        ufw:
          state: enabled
      - name: Show Firewall 
        command: ufw status 
        register: firewall_status 
      - name: Show Firewall status 
        debug: 
          msg: "{{firewall_status.stdout}}"



